### ISSUE TITLE
Does not work with gwf 1.7.0

### ISSUE THREAD

**Issue by micknudsen** [micknudsen/gwf-utilization#10]
Something has happened to the `_call_generic` function in `gwf` 1.7.0.

```
$ gwf utilization

Warning: entry point could not be loaded. Contact its author for help.


Traceback (most recent call last):
  File "/home/michaelk/miniconda3/envs/banjohest/lib/python3.8/site-packages/click_plugins/core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "/home/michaelk/miniconda3/envs/banjohest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/michaelk/miniconda3/envs/banjohest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/michaelk/miniconda3/envs/banjohest/lib/python3.8/site-packages/gwf_utilization/main.py", line 12, in <module>
    from gwf_utilization.accounting import get_jobs
  File "/home/michaelk/miniconda3/envs/banjohest/lib/python3.8/site-packages/gwf_utilization/accounting.py", line 3, in <module>
    from gwf.backends.slurm import _call_generic
ImportError: cannot import name '_call_generic' from 'gwf.backends.slurm' (/home/michaelk/miniconda3/envs/banjohest/lib/python3.8/site-packages/gwf/backends/slurm.py)
```

**Comment by dansondergaard** [comment]
You used an internal API (thus the underscore). It changed ;-)

**Comment by micknudsen** [comment]
Is there no way to call `sacct` in gwf 1.7.0?

**Comment by dansondergaard** [comment]
There never has been. Just use the subprocess module. The `_call_generic` function was an internal helper function for the Slurm backend and since the Slurm backend has been rewritten the helper function is now gone. But you were never supposed to use it anyway.
